#ifndef _DEFINES_HPP
#define _DEFINES_HPP

#define WINWIDTH 800
#define WINHEIGHT 600
#define BPP 32

#define PLAYERWIDTH 32
#define PLAYERHEIGHT 48
#define PLAYERSPEEDINCREASE 0.1
#define PLAYERGRAVITY 0.1
#define PLAYERJETPACKPOWER 0.2
#define PLAYERBLEEDPOINT 22
#define WALLBOUNCEABSORB 0.5
#define MAXSPEED 6.0
#define INVULNERABILITYTIME 250

#define PICKUPFALLSPEED 3
#define PICKUPSPAWNWAIT 500

#define BULLETDAMAGE 10
#define ROCKETDAMAGE 10 
#define CHAINSAWDAMAGE 3
#define FLAMEDAMAGE 0.8

#define SMGWAIT 10
#define SMGAMMO 25

#define ROCKETWAIT 50
#define ROCKETAMMO 2

#define FLAMEWAIT 2 
#define FLAMEAMMO 200

#define SHOTGUNWAIT 30
#define SHOTGUNAMMO 15

#define CRATEWIDTH 39
#define CRATEHEIGHT 30

#define BLEEDMODE
// #define MIXER
// #define SOUNDS
// #define MUSIC

enum PLAYERKEYS { KUP, KDOWN, KLEFT, KRIGHT, KSHOOT };
enum DIRECTION { UP, DOWN, LEFT, RIGHT, DNONE };
enum WEAPONTYPE { NONE, CHAINSAW, SMG, BAZOOKA, FLAMETHROWER, SHOTGUN };
enum BULLETTYPE { BULLET, ROCKET, FLAME, SHELL };
enum ENTITY { ENONE, EPLAYER, EBULLET, EROCKET, ECHAINSAW, EFLAME, EPICKUP };
enum PLAYERS { RED, BLUE };

#endif
